Refactoring
AlgorithmsTheory/TuringMachine pull request #1
Opened 2019-03-10 16:49 UTC by SorokinStanislav

* add maven
* add gitignore
* add packages
* add readme
* refactoring

2019-03-13 20:41 UTC, KipDurron requested changes
остальное ок

2019-03-13 20:41 UTC, KipDurron commented on src/main/java/ru/mephi22/turing/Rules.java
> +    Rules(){
не хватает пробела перед фигурной скобкой

2019-03-13 20:41 UTC, KipDurron commented on src/main/java/ru/mephi22/turing/TapeStore.java
> +    TapeStore(ArrayList<String> data){
не хватает пробела перед фигурной скобкой

2019-03-13 20:41 UTC, KipDurron commented on src/main/java/ru/mephi22/turing/TapeStore.java
> +        for (Tape tape : tapes) result.append(tape.toString()).append(" ");
Нужны ли фигурные скобки для тела цикла for?

2019-03-13 20:41 UTC, KipDurron commented on src/main/java/ru/mephi22/turing/TuringMachine.java
> +        } catch (Exception ex) {
Может стоит указать конкретнее тип исключения?

2019-03-13 22:14 UTC, SorokinStanislav commented on src/main/java/ru/mephi22/turing/Rules.java
> +    Rules(){
ок

2019-03-13 22:14 UTC, SorokinStanislav commented on src/main/java/ru/mephi22/turing/TapeStore.java
> +    TapeStore(ArrayList<String> data){
ок

2019-03-13 22:15 UTC, SorokinStanislav commented on src/main/java/ru/mephi22/turing/TapeStore.java
> +        for (Tape tape : tapes) result.append(tape.toString()).append(" ");
да, стоит, поставил скобки

2019-03-13 22:20 UTC, SorokinStanislav commented on src/main/java/ru/mephi22/turing/TuringMachine.java
> +        } catch (Exception ex) {
Изменил на `RuntimeException`, потому что ничего проверяемые исключения тут не бросает. Но видимо отлов нужен и что-то ловил. Дальнейший анализ будет проведен на более поздних стадиях обновления эмулятрора.

2019-03-14 17:56 UTC, KipDurron approved these changes

2019-03-14 18:06 UTC, merged